name: Infra workflow

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
env:
  ECR_REPOSITORY: myrepo
  IMAGE_TAG: latest
  K8S_DEPLOYMENT: patient-service
  K8S_NAMESPACE: default

jobs:
 deploy-infra:
    name: Deploy Infrastructure with Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.0

      - name: Initialize Terraform
        run: |
          cd terraform
          terraform version
          terraform init
                    
      - name: Validate Terraform    
        run: |
          cd terraform
          terraform fmt
          
      - name: "Terraform Validate"
        run: |
          cd terraform
          terraform validate

      - name: "Terraform Plan"
        run: |
          cd terraform
          terraform Plan         
          
      - name: Apply Terraform Configuration
        run: |
          if: github.ref == 'refs/heads/main'
          cd terraform
          terraform apply -auto-approve
