name: "Infra CI/CD Pipeline"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment to deploy (dev/staging/prod)"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
 deploy-infra:
    name: Deploy Infrastructure with Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.0

      - name: Initialize Terraform
        run: |
          cd terraform
          terraform version
          terraform init
                    
      - name: Validate Terraform    
        run: |
          cd terraform
          terraform fmt
          
      - name: "Terraform Validate"
        run: |
          cd terraform
          terraform validate

      - name: "Terraform Plan"
        run: |
          cd terraform
          terraform Plan         
          
      - name: Apply Terraform Configuration
        run: |
          if: github.ref == 'refs/heads/main'
          cd terraform
          terraform apply -auto-approve
